local CreateUI = loadstring(game:HttpGet("https://raw.githubusercontent.com/xplue31/plue-lib/main/Source.lua", true))
local UI = CreateUI("cum shooter script", Enum.KeyCode.B)
local tab = UI.Tab("Good Shit MF")
tab.Label("hi wASADIQWDSKADSADAS")
tab.Button("sadkmaskdas", function()
    print("Hi!")
end)
UI.CreateUISettings()